[package]
name = "opendal-mbt-wasm-bridge"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gloo-timers = { version = "=0.3.0", features = ["futures"] }
opendal = { version = "=0.58.1", default-features = false }
thiserror = "=2.0.20"
wasm-bindgen-futures = "=0.4.77"
