const DEFAULT_IMPORT_MODULE = "opendal_mbt_bridge";
const DEFAULT_HOST_MODULE = "opendal_mbt_host";
const MOONBIT_FFI_MODULE = "moonbit:ffi";
const TASK_PENDING = 1;
const TASK_READY = 2;

function createTaskHost(bridgeExports) {
  let disposed = false;
  const timers = new Set();

  function schedule(callback) {
    const timer = setTimeout(() => {
      timers.delete(timer);
      callback();
    }, 0);
    timers.add(timer);
  }

  function waitTask(handle, callback) {
    if (disposed) {
      return;
    }
    if (typeof callback !== "function") {
      throw new TypeError("task callback must be a function");
    }
    const poll = () => {
      if (disposed) {
        return;
      }
      const state = bridgeExports.opendal_mbt_wasm_task_state(handle);
      if (state === TASK_PENDING) {
        schedule(poll);
      } else if (state === TASK_READY) {
        callback(handle);
      }
    };
    queueMicrotask(poll);
  }

  return {
    imports: { wait_task: waitTask },
    dispose() {
      disposed = true;
      for (const timer of timers) {
        clearTimeout(timer);
      }
      timers.clear();
    },
  };
}

function isResponse(value) {
  return typeof Response !== "undefined" && value instanceof Response;
}

async function toModule(source) {
  if (source instanceof WebAssembly.Module) {
    return source;
  }
  if (isResponse(source)) {
    if (!source.ok) {
      throw new Error(`could not fetch Wasm module: HTTP ${source.status}`);
    }
    const fallback = source.clone();
    try {
      return await WebAssembly.compileStreaming(Promise.resolve(source));
    } catch {
      return WebAssembly.compile(await fallback.arrayBuffer());
    }
  }
  if (source instanceof URL && source.protocol === "file:") {
    if (typeof process === "undefined" || !process.versions?.node) {
      throw new TypeError("file: Wasm URLs are only supported by the Node loader");
    }
    const { readFile } = await import("node:fs/promises");
    return WebAssembly.compile(await readFile(source));
  }
  if (source instanceof URL || typeof source === "string") {
    return toModule(await fetch(source));
  }
  if (source instanceof ArrayBuffer || ArrayBuffer.isView(source)) {
    return WebAssembly.compile(source);
  }
  throw new TypeError(
    "Wasm source must be a URL, Response, WebAssembly.Module, ArrayBuffer, or typed array",
  );
}

async function instantiateBridge(source, imports, initializer) {
  if (initializer === undefined) {
    return WebAssembly.instantiate(await toModule(source), imports);
  }
  if (typeof initializer !== "function") {
    throw new TypeError("bridgeInitializer must be a function");
  }
  const exports = await initializer({ module_or_path: source });
  if (exports === null || typeof exports !== "object") {
    throw new TypeError("bridgeInitializer did not return Wasm exports");
  }
  return { exports };
}

/**
 * Load the Rust OpenDAL bridge and a MoonBit Wasm consumer wired to it.
 *
 * The bridge initializer is the default export generated by wasm-bindgen. The
 * consumer only imports scalar bridge functions. Rust and MoonBit retain
 * separate memories and allocators; the MoonBit facade performs explicit byte
 * copies through generation-checked bridge handles.
 */
export async function loadOpenDalMoonBit({
  bridge,
  bridgeInitializer,
  moonbit,
  imports = {},
  bridgeImports = {},
  importModule = DEFAULT_IMPORT_MODULE,
  hostModule = DEFAULT_HOST_MODULE,
}) {
  const bridgeInstance = await instantiateBridge(
    bridge,
    bridgeImports,
    bridgeInitializer,
  );
  let taskHost;
  try {
    const moonbitModule = await toModule(moonbit);
    const existing = imports[importModule] ?? {};
    const existingHost = imports[hostModule] ?? {};
    const existingMoonBitFfi = imports[MOONBIT_FFI_MODULE] ?? {};
    taskHost = createTaskHost(bridgeInstance.exports);
    const moonbitImports = {
      ...imports,
      [importModule]: {
        ...existing,
        ...bridgeInstance.exports,
      },
      [hostModule]: {
        ...existingHost,
        ...taskHost.imports,
      },
      [MOONBIT_FFI_MODULE]: {
        make_closure: (funcref, closure) => funcref.bind(null, closure),
        ...existingMoonBitFfi,
      },
    };
    const moonbitInstance = await WebAssembly.instantiate(
      moonbitModule,
      moonbitImports,
    );
    let disposed = false;
    return {
      exports: moonbitInstance.exports,
      bridge: bridgeInstance,
      moonbit: moonbitInstance,
      dispose() {
        if (disposed) {
          return;
        }
        disposed = true;
        taskHost.dispose();
        bridgeInstance.exports.opendal_mbt_wasm_teardown();
      },
    };
  } catch (error) {
    taskHost?.dispose();
    bridgeInstance.exports.opendal_mbt_wasm_teardown?.();
    throw error;
  }
}

export default loadOpenDalMoonBit;
